<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">

<?php
$viewModel = $this->getViewModel();
$products = [
    [
        'image' => $viewModel->getViewFileUrl('MiniOrange_SSO::images/idp_upgrade.png'),
        'alt' => '',
        // 'badge' => 'NEW',
        'title' => 'SAML IDP',
        'description' => 'Login into any third party applications using Magento credentials.',
        'link' => 'https://commercemarketplace.adobe.com/miniorange-inc-idpsaml.html'
    ],
    [
        'image' => $viewModel->getViewFileUrl('MiniOrange_SSO::images/twofa_upgrade.png'),
        'alt' => 'Two-Factor Authentication',
        //'badge' => 'POPULAR',
        'title' => 'Two-Factor Authentication',
        'description' => 'Add a second layer of authentication to secure your Magento store frontend & backend accounts.',
        'link' => 'https://commercemarketplace.adobe.com/miniorange-inc-miniorange-2fa.html'
    ],
    [
        'image' => $viewModel->getViewFileUrl('MiniOrange_SSO::images/scim_upgrade.png'),
        'alt' => 'Scim User Provisioning',
        //'badge' => 'POPULAR',
        'title' => 'User Provisioning & Sync',
        'description' => 'Automate real-time two-way user sync, including creation, updates, and deletions, between your applications and Magento.',
        'link' => 'https://commercemarketplace.adobe.com/miniorange-inc-scim.html'
    ],
    [
        'image' => $viewModel->getViewFileUrl('MiniOrange_SSO::images/otp_upgrade.png'),
        'alt' => 'Mobile Login',
        //'badge' => 'POPULAR',
        'title' => 'Mobile Login',
        'description' => 'Log in to Magento store using mobile number/email — no password required.',
        'link' => 'https://commercemarketplace.adobe.com/miniorange-inc-otp-verification.html'
    ],
    [
        'image' => $viewModel->getViewFileUrl('MiniOrange_SSO::images/ldap_upgrade.png'),
        'alt' => 'LDAP Login',
        //'badge' => 'POPULAR',
        'title' => 'LDAP / Active Directory Login Integration',
        'description' => 'Log in to Magento using LDAP/AD credentials from Active Directory, OpenLDAP, OpenDS, FreeIPA, Synology, and more.',
        'link' => 'https://commercemarketplace.adobe.com/miniorange-inc-miniorange-ldap.html'
    ],
    [
        'image' => $viewModel->getViewFileUrl('MiniOrange_SSO::images/google_upgrade.png'),
        'alt' => 'Google One Tap Login',
        //'badge' => 'POPULAR',
        'title' => 'Google One Tap Login',
        'description' => 'One Click sign in or register on your Magento store using Google Account credentials.',
        'link' => 'https://commercemarketplace.adobe.com/miniorange-inc-google-one-tap-login.html'
    ],
    [
        'image' => $viewModel->getViewFileUrl('MiniOrange_SSO::images/security_upgrade.png'),
        'alt' => 'Security Suite',
        //'badge' => 'POPULAR',
        'title' => 'Security Suite',
        'description' => 'Secure your Magento store with robust security tools.',
        'link' => 'https://plugins.miniorange.com/magento-2-security-suite-extension'
    ],
    [
        'image' => $viewModel->getViewFileUrl('MiniOrange_SSO::images/social_upgrade.png'),
        'alt' => 'Social Login & Share',
        //'badge' => 'POPULAR',
        'title' => 'Social Login & Share',
        'description' => 'Log in to Magento using social login credentials, including Facebook, Instagram, Google, Twitter, LinkedIn, and more.',
        'link' => 'https://commercemarketplace.adobe.com/miniorange-inc-miniorange-social-login.html'
    ],
];

$plan_name = 'Security Suite Free';
$versions = 'v1.0.0';
?>
<!-- Breadcrumb -->

<!-- Main Content -->
<div class="main-content">
    <div class="container">
        <div class="main-panel_upgrade background_gray">
            <div class="panel-content">
                <!-- Ultra Simple Upgrade Banner -->
                <div class="upgrade-banner">
                    <div class="plan-info">
                        <div class="plan-status">Current Plan</div>
                        <div class="panel-title_report"><?php echo $plan_name; ?> <span
                                class="plan-version">Version <?php echo $versions; ?></span>

                            <!-- <span>
                            <a href="https://plugins.miniorange.com/magento-oauth-single-sign-on-sso#pricing" target="_blank" class="btn btn-primary" style="float: right;font-size:1.4rem">
                                <i class="fas fa-arrow-circle-up"></i>
                                Click Here to Upgrade
                            </a>

                            </span> -->
                        </div>

                    </div>
                    <span>
                            <a href="https://plugins.miniorange.com/magento-2-security-suite-extension"
                               target="_blank" class="btn btn-primary" style="float: right;font-size:1.4rem">
                                <i class="fas fa-arrow-circle-up"></i>
                                Click Here to Upgrade
                            </a>

                        </span>

                </div>
            </div>
        </div>


        <!-- Related Products -->
        <div class="main-panel_upgrade">
            <div class="panel-header">
                <div class="panel-title-container">
                    <h2 class="panel-title">Related Products</h2>
                    <p class="panel-subtitle">Enhance your Magento store with our complementary extensions</p>
                </div>
                <div class="panel-actions">
                    <div class="btn btn-outline" onclick="openAllProducts()">
                        <i class="fas fa-th-large"></i>
                        View All Products
                    </div>
                    <!-- <a href="#" class="btn btn-outline">
                        <i class="fas fa-th-large"></i>
                        View All Products
                    </a> -->
                </div>
            </div>

            <div class="panel-content">
                <div class="products-grid">
                    <?php foreach ($products as $product): ?>
                        <div class="product-card">
                            <div class="product-image">
                                <img src="<?php echo $product['image']; ?>" loading="lazy" alt="<?php echo $product['alt']; ?>">
                            </div>
                            <div class="product-details">
                                <h3 class="product-title"><?php echo $product['title']; ?></h3>
                                <p class="product-description"><?php echo $product['description']; ?></p>
                                <div class="product-actions">
                                    <a href="<?php echo $product['link']; ?>" target="_blank"
                                       class="btn btn-primary position">View Details</a>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    function openAllProducts() {
        window.open('https://plugins.miniorange.com/magento', '_blank');
    }
</script>